- hosts: aws_vm
  become: true
  tasks:
  - name: Installing libreswan
    ansible.builtin.dnf:
      name: libreswan
      state: latest

  - name: Copy connections.conf file
    ansible.builtin.template:
      src: ./templates/connections.conf
      dest: /etc/ipsec.d
      owner: root
      group: root
      mode: '0755'

  - name: Copy connections.secrets file
    ansible.builtin.template:
      src: ./templates/connections.secrets
      dest: /etc/ipsec.d
      owner: root
      group: root
      mode: '0755'

  - name: Copy sysctl.conf file
    copy:
      src: ./files/sysctl.conf
      dest: /etc/
      owner: root
      group: root
      mode: 0644
  - name: Restart service httpd, in all cases
    ansible.builtin.service:
      name: ipsec
      state: restarted
