- hosts: desktops
  tasks:
  - name: Install ldap packages on client
    ansible.builtin.package:
      name: 
        - libnss-ldap
        - libpam-ldap
        - ldap-utils
        - nscd
      state: present
    become: true
  - name: Copy file and set owner and permissions
    copy:
      src: ./files/ldap.conf
      dest: /etc/ldap.conf
      owner: none
      group: none
      mode: 0644
    become: true


