- hosts: webserver
  tasks:
  - name: Add repository
    command: "/bin/yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
    become: true  
  - name: Install docker packages on webserver
    ansible.builtin.package:
      name: 
        - docker-ce 
        - docker-ce-cli
        - containerd.io 
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
    become: true
  - name: Stopping httpd
    ansible.builtin.service:
      name: httpd
      state: stopped
    become: true
- hosts: desktops
  tasks:
  - name: Install ldap packages on client
    ansible.builtin.package:
      name: 
        - libnss-ldap
        - libpam-ldap
        - ldap-utils
        - nscd
      state: present
    become: true
  - name: Copy ldap.conf file
    copy:
      src: ./files/ldap.conf
      dest: /etc/ldap.conf
      owner: root
      group: root
      mode: 0644
    become: true
  - name: Copy nsswitch.conf file
    copy:
      src: ./files/nsswitch.conf
      dest: /etc/nsswitch.conf
      owner: root
      group: root
      mode: 0644
    become: true
  - name: Copy common-password file
    copy:
      src: ./files/common-password
      dest: /etc/pam.d/common-password
      owner: root
      group: root
      mode: 0644
    become: true
  - name: Copy common-session file
    copy:
      src: ./files/common-session
      dest: /etc/pam.d/common-session
      owner: root
      group: root
      mode: 0644
    become: true



