- hosts: webserver
  become: true
  tasks:
  - name: Add repository
    command: "/bin/yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
    become: true  
  - name: Install docker packages on webserver
    ansible.builtin.package:
      name: 
        - docker-ce 
        - docker-ce-cli
        - containerd.io 
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
  - name: Checking to see if ldap container is installed
    docker_container:
      name: ldap-service
      state: started
      image: "osixia/openldap:latest"
      pull: true
      ports:
        - "389:389"
        - "636:636"
      env:
        - LDAP_ORGANISATION:"AUTOZONE" 
        - LDAP_DOMAIN:"AUTOZONE.com" 
        - LDAP_ADMIN_PASSWORD:"test123" 
  - name: Stopping httpd
    ansible.builtin.service:
      name: httpd
      state: stopped
- hosts: desktops
  tasks:
  - name: Install ldap packages on client
    ansible.builtin.package:
      name: 
        - libnss-ldap
        - libpam-ldap
        - ldap-utils
        - nscd
      state: present
  - name: Copy ldap.conf file
    copy:
      src: ./files/ldap.conf
      dest: /etc/ldap.conf
      owner: root
      group: root
      mode: 0644
  - name: Copy nsswitch.conf file
    copy:
      src: ./files/nsswitch.conf
      dest: /etc/nsswitch.conf
      owner: root
      group: root
      mode: 0644
  - name: Copy common-password file
    copy:
      src: ./files/common-password
      dest: /etc/pam.d/common-password
      owner: root
      group: root
      mode: 0644
  - name: Copy common-session file
    copy:
      src: ./files/common-session
      dest: /etc/pam.d/common-session
      owner: root
      group: root
      mode: 0644



