version: "3"
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - PYTHONUNBUFFERED=1
    volumes:
    - /var/log/:/fluentd/log/files/ #  Path to syslog file that is read by fluent.conf
    - ./configurations:/fluentd/etc/
    - ./output/:/output/ # This directory will hold the script that hit the paloalto api
    logging:
      driver: "local"