version: "3"
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - PYTHONUNBUFFERED=1
    volumes:
    - /var/log/:/fluentd/log/files/ #  Path to syslog file that is read by fluent.conf
    - ./configurations:/fluentd/etc/
    - ./output/:/output/ # This directory will hold the script that hit the paloalto api
    logging:
      driver: "local"
  #  This app will hold the ldap server with all needed variables.
  ldap-service:
    container_name: ldap-service
    image: osixia/openldap:latest
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=AUTOZONE
      - LDAP_DOMAIN=AUTOZONE.com
      - LDAP_ADMIN_PASSWORD=test123
    logging:
      driver: "syslog" 
  #  This app will be used to hold the server that manages the
  #  ldap server.
  phpldapadmin-service:
    container_name: phpldapadmin-service
    image: osixia/phpldapadmin:latest
    ports:
      - "443:443"
    links:
      - "ldap-service:ldap-host"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host 
